### ISSUE TITLE
Filter columns in Milestones view

### ISSUE THREAD

**Issue by Toilal** [huboard/huboard-web#108]
I'm not sure it's the right place to ask for features, but ...

In Milestones view, it would be great to have the possibility to filter on defined columns .

In my project, I have a `Idea/Discussion` column and a `Backlog` column, and I want to assign milestones from `Backlog` columns only right in the Milestones view. 

Today, I have to do it in the Task view, but it's not really appropriate because it requires to open all issues from backlog column, and set the milestone manually for each of them. With the columns filter in Milestones view, it would be possible to perform this more quickly with drag&drop.

Thanks for this great tool !

**Comment by discorick** [comment]
Thats a good point - while in most scenarios the issues in the "No Milestone" column belong to the Backlog, I can see how in your use case a column filter would speed things up. Not sure if/when we will pick this up but I think its a great idea.

**Comment by Toilal** [comment]
Thanks :)

**Comment by Toilal** [comment]
I'm not a Ruby developer, so I can't submit a pull request sorry, but keep the good work, huboard is a great tool !

**Comment by jeffclary** [comment]
:+1:
