### ISSUE TITLE
Set the column at creation time

### ISSUE THREAD

**Issue by thuey** [huboard/huboard-web#113]
First of all, let me say you guys have done an awesome job with huboard. Probably the biggest pain point for me is that i can't create an issue and assign it to a column at the same time. Maybe I'm overlooking something about why this might not be desirable. Just to make a case for it though, our default column is Backlog. However, when creating a  new issue, we often want to put it directly into the second column "Todo". Is this anywhere on your roadmap?

**Comment by dahlbyk** [comment]
Closing this as a duplicate of https://github.com/huboard/huboard/issues/596.
