### ISSUE TITLE
Feature Request: emoji support

### ISSUE THREAD

**Issue by eggsby** [huboard/huboard-web#119]
I really enjoy using emojis in my github commit messages but emojis don't render properly on huboard.

**Comment by eggsby** [comment]
For an example, visit: https://huboard.com/huboard/huboard-web#/issues/112929905

:+1:

**Comment by discorick** [comment]
@eggsby 

![uploads/6668fead-b994-4cda-8c18-b66f787af8ea/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6668fead-b994-4cda-8c18-b66f787af8ea%2Fblob)
