### ISSUE TITLE
Constrain commit messages to subject line

### ISSUE THREAD

**Issue by cbeams** [huboard/huboard-web#138]
This appears to be a partially implemented feature:

![image](https://cloud.githubusercontent.com/assets/301810/10849957/86d2be4a-7f23-11e5-8b55-82ff66aece17.png)

Please advise, thanks. My team and I are evaluating HuBoard, so it's good to know what to expect when we see things like this.

**Comment by discorick** [comment]
Hey @cbeams - This comes from a constraint in GitHubs API that made it impossible to know where a commit referenced from an external repo came from. After reaching out to their API team they kindly patched this for us, and I opened PR #133 this week to adapt those changes. 

There is one remaining constraint, while we can now provide a link and the sha to the external repo commit, there is still no way to gather the commit message without making n+1 API calls. This has also been filed with the GH API Team.

**Comment by cbeams** [comment]
Excellent, thanks for the quick response.

**Comment by cbeams** [comment]
Commits messages are now showing up in HuBoard, but are doing so in a way that violates git commit message formatting conventions.

Actual behavior: Commit message subject and body are being concatenated. e.g.:

![screen shot 2015-11-06 at 1 45 22 pm](https://cloud.githubusercontent.com/assets/301810/10997344/a8028c12-848c-11e5-9bb1-be4c1f2f242f.png)


Expected behavior: Only the subject of the commit message should show up, as is the case on GitHub, e.g.:

![screen shot 2015-11-06 at 1 44 20 pm](https://cloud.githubusercontent.com/assets/301810/10997328/879193d8-848c-11e5-8175-71886ea4d1fc.png)

**Comment by discorick** [comment]
@cbeams this is a case of the GitHub API not differentiating between the two. The subject + body are wrapped together in the `message` key as you can see here: https://developer.github.com/v3/repos/commits/#get-a-single-commit

**Comment by cbeams** [comment]
Could you simply parse the output of that API call the way that tools like `git shortlog` and `git log --oneline` and the GitHub UI do, such that you display only the commit subject line?

**Comment by dahlbyk** [comment]
> Could you simply parse the output of that API call the way that tools like `git shortlog` and `git log --oneline` and the GitHub UI do, such that you display only the commit subject line?

Yep, we should do this.

**Comment by dahlbyk** [comment]
To be more explicit, to align with Git `--oneline` behavior, we should split commit messages at `\n\s*\n`, using the first part as the title and the rest (if applicable) as a body.

Interestingly, GitHub's message parsing does not seem to agree with Git's. https://github.com/huboard/huboard-web/commit/d44b955 has a `\n` that GitHub splits on but Git does not.

```
$ git log d44b955 --oneline -n1
d44b955 suppresses Stripe warnings in enterprise because we don't need to load stripe
```

I'd suggest we align with Git.

**Comment by cbeams** [comment]
Actually, d44b955 is a bad example. Note below how, in the full `git log` output, the subject line was manually wrapped by @rauhryan without a [blank line separating the subject from the body](http://chris.beams.io/posts/git-commit/#separate).

```
$ git log -1 d44b955
commit d44b955657b1b6fe1779e86657844ab2416fd85d
Author: Ryan Rauh <rauh.ryan@gmail.com>
Date:   Mon Apr 18 15:52:32 2016 -0500

    suppresses Stripe warnings in enterprise because we
    don't need to load stripe
```

Now, when rendering that same commit with `git log --oneline`, notice how `git` simply joins the two lines into one:
```
$ git log -1 d44b955 --oneline
d44b955 suppresses Stripe warnings in enterprise because we don't need to load stripe
```

> GitHub's message parsing does not seem to agree with Git's

This is not really the case. Looking at [huboard-web/commit/d44b955](https://github.com/huboard/huboard-web/commit/d44b955) is the equivalent of `git log d44b955` without `--oneline`. Here, GitHub—like `git`—is simply rendering the text of the commit message as it was originally written, with newlines and blank lines (or lack thereof) where the author placed them:

![image](https://cloud.githubusercontent.com/assets/301810/14697065/f0507b24-0780-11e6-8621-8b7732d50240.png)

Looking at d44b955 in GitHub's _commit list_ view ([huboard-web/commits/d44b955](https://github.com/huboard/huboard-web/commit/d44b955)), on the other hand, is GitHub's equivalent of `git log d44b955 --oneline`, but notice here how GitHub—_unlike_ `git`—does respect the `\n` in the original author's (badly formed) commit message:

![image](https://cloud.githubusercontent.com/assets/301810/14697046/d26b0426-0780-11e6-894c-24832fe7796f.png)

> I'd suggest we align with Git.

Given the above, I'd conclude the opposite. I would make the same decisions GitHub makes about showing users the most intelligible commit subject line possible, even if it requires deviating slightly from the way `git` proper works. Specifically, here are GitHub's deviations from the `git` norm (when rendering commit subject lines) that you could adopt in HuBoard:

1. For commits that do not place a blank line between subject and body, render as subject line whatever text comes before the first `\n`;
2. [Truncate long subject lines at 69 characters](http://chris.beams.io/posts/git-commit/#limit-50) and append an ellipsis to indicate truncation has occurred.

Note that these rules can be additive. That is rule 1 can be applied, and then rule 2 can be applied to its outcome.

Hope this helps.

**Comment by dahlbyk** [comment]
From [`git commit` docs](https://git-scm.com/docs/git-commit#_discussion):

> The text up to the first blank line in a commit message is treated as the commit title, and that title is used throughout Git.

I'll fully admit to being pedantic here, but I don't think "badly formed" is a fair characterization. Longer than recommended, but only that. The same would be true for a commit with several lines but no empty line delineating the start of the body—that the title is way too long doesn't change that it's the title.

That said, you are spot on in the commits vs commit distinction. Beyond that, I could rationalize the GitHub behavior as explicitly not following `--oneline` convention because the remainder of the full message is available via toggle. We're not shown the title, but rather the first line.

So the question for HuBoard is: should we show a (possibly truncated) title, according to Git's definition, or the full commit message (with the first line visible before toggle)?

**Comment by cbeams** [comment]
> I don't think "badly formed" is a fair characterization. Longer than recommended, but only that.

I'll concede that in this context :)

> So the question for HuBoard is, should we:
> 1. show a (possibly truncated) title, according to Git's definition, or
> 2. show the full commit message (with the first line visible before toggle)?

I'd say (3): show up to 69 characters of the first line, and never include anything after a `\n`.

The rationale for this approach is that many folks simply don't know about the "blank line separator" between title and body, and so they omit it. This means that in practice, approach (1) above would result in HuBoard would often showing titles that join the _intended_ title (first line) and _intended_ body (the subsequent lines) as one line. This would mean lots of mangled-looking truncated titles.

Showing up to 69 characters of the first line, on the other hand, always respects the good behavior of folks who understand how to properly format a git commit message, and provides a reasonable truncation approach to those who forget to include the separating blank line, or who tend to write run-on messages at the command line with `git commit -m"..."`.

**Comment by dahlbyk** [comment]
> I'd say (3): show up to 69 characters of the first line, and never include anything after a \n.

Works for me. We might reasonably continue to rely on `text-overflow: ellipsis` instead of explicitly truncating to 69 characters, but you've convinced me that anything beyond the first `\n` is potentially confusing. :bow: 

As an aside, thanks for http://chris.beams.io/posts/git-commit/! I refer others to it often. :clap:
