### ISSUE TITLE
Getting Dalli::RingError in DashboardController#index after redirect from Github authorize

### ISSUE THREAD

**Issue by chrisfelix82** [huboard/huboard-web#146]
I am getting the following output.  The line dalli.get(key) is highlighted red.  Any ideas?:

cache.with do |dalli|
          logger.debug("Cache read: #{key}")
          dalli.get(key)
        end
      end

**Comment by discorick** [comment]
Hey @chrisfelix82, is this on a clean provision ? It's most likely something going on with the memcache server.

**Comment by chrisfelix82** [comment]
I've set it all up within a docker container so I'm not sure.

**Comment by discorick** [comment]
Ok, we have not done much with docker + huboard at this point, I would make sure you have memcached running on localhost:11211 on the container

**Comment by chrisfelix82** [comment]
Yes it is. I even tried creating another container just for memcache with no luck :(

**Comment by discorick** [comment]
Have you set something like: `MEMCACHIER_SERVERS=127.0.0.1:11211 ` in your .env file?

**Comment by chrisfelix82** [comment]
It was set to 0.0.0.0:11211 then I tried local host. I'll try that next. Thanks

**Comment by chrisfelix82** [comment]
My .env file looks like this:

```
HUBOARD_ENV=OSS

SECRET_KEY=abc1234defg
SESSION_SECRET=herpderp

SOCKET_BACKEND=/site/pubsub
SELF_HOST_FAYE=true

MEMCACHIER_SERVERS=127.0.0.1:11211

#STRIPE_SECRET_KEY=(enable production mode for this)
#STRIPE_PUBLISHABLE_API=(enable production mode for this)

COUCH_DATABASE=huboard
COUCH_URL=http://127.0.0.1:5984

GITHUB_AUTH_STRATEGY=personal_token
GITHUB_CLIENT_ID=***
GITHUB_SECRET=***
GITHUB_API_ENDPOINT=https://api.github.com
GITHUB_WEB_ENDPOINT=https://github.com

REDIS_URL=redis://redis:6379

AWS_ACCESS_KEY_ID=(Only Need for Image Upload)
AWS_SECRET_ACCESS_KEY=(Only Need for Image Upload)
#AWS_S3_BUCKET=dev.huboard.com
```

**Comment by chrisfelix82** [comment]
OK so I got past the issue.  I had made a mistake and taken memcache out of the Procfile.  Adding it back got me past the issue.  I am having another issue where the task board loads a blank page.  Next thing to debug... getting close though :) Thanks for the help so far

**Comment by chrisfelix82** [comment]
vendor.js and app.js are both 404

**Comment by discorick** [comment]
Have you build with App yet? `cd ember-app && ember build`

**Comment by chrisfelix82** [comment]
:/ I'm honestly hacking my way through this as I am not familiar outside node.js, Java and Angular apps for web.  never done ember or ruby stuff.  Thanks for the pointer.  I assume npm install and bower install from ember-app and then ember build?

**Comment by discorick** [comment]
I just have asked first if you've seen our wiki! This should help: https://github.com/rauhryan/huboard/wiki/Local-Development

**Comment by chrisfelix82** [comment]
Thanks! No I had not. my bad. I am getting

 /usr/bin/env: node: No such file or directory
INFO[0389] The command [/bin/sh -c cd /app/ember-app && npm install ember-cli -g && npm install && ember build] returned a non-zero code: 127 

when doing cd ember-app && npm install ember-cli -g && npm install && ember build

**Comment by chrisfelix82** [comment]
ok may be a symlink that I need ln -s /usr/bin/nodejs /usr/bin/node

**Comment by chrisfelix82** [comment]
Thanks for all the help, I finally got it all working! :)  Now to just make it production ready with cloudant and splitting out Redis.

**Comment by discorick** [comment]
@chrisfelix82 woohoo! Glad your up and running. By the way, if you end up forking us and adding cool features feel free to open up a PR!
