### ISSUE TITLE
[UX] Non-admin organization member should have an error state when trying to view account settings. 

### ISSUE THREAD

**Issue by rauhryan** [huboard/huboard-web#147]

**Comment by dahlbyk** [comment]
@iheanyi did you fix this with your Accounts work? @discorick can you confirm?

**Comment by iheanyi** [comment]
@dahlbyk I'm not sure, I didn't even realize I had been assigned to this issue, haha.

**Comment by dahlbyk** [comment]
OK, confirmed that without sufficient permissions you are redirected to https://huboard.com/settings/profile#/not-authorized.

> Hold on! This organization either does not exist or you do not have access.
>
> Here are the organizations that we were able to get from the GitHub API.
