### ISSUE TITLE
Enable Intercom on HuBoard marketing/login materials

### ISSUE THREAD

**Issue by discorick** [huboard/huboard-web#162]
Right now intercom is not enabled for the marketing materials. 

We have a partial in `app/views/shared/_analytics.html.erb` where we define client-side Segment behavior on line 4. Need to figure out a way to make this work when `current_user.id` is null (pre login) so that we can still service anonymous users. 

Related materials would be the segment.com documentation, also take a look at the segment intercom integration.

**Comment by dahlbyk** [comment]
@petey-rock where did we leave off on this? Was it that Intercom requires a non-anonymous user?

**Comment by dahlbyk** [comment]
@petey-rock bump!

**Comment by dahlbyk** [comment]
> Was it that Intercom requires a non-anonymous user?

Pretty sure this is the case. If I'm logged in, I see Intercom on `/pricing`.
