### ISSUE TITLE
[SAAS] Load Details method throws exception if not part of an organization in accounts

### ISSUE THREAD

**Issue by iheanyi** [huboard/huboard-web#167]
Whenever a user attempts to navigate to a organization at `settings/profile` that they are not a part of, they get thrown a white screen of death. This should probably show them a message stating that they are not a part of the organization / do not have permission to edit, and perhaps send them a link back to their main profile page.

![uploads/d166edc5-c140-4a77-9430-13612d7c7960/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fd166edc5-c140-4a77-9430-13612d7c7960%2Fblob)

Closed by huboard/huboard-web#158

**Comment by discorick** [comment]
Thats Ugly!

**Comment by iheanyi** [comment]
FInalized and fixed in this commit: https://github.com/huboard/huboard-web/commit/ce11177997e25954b21f3885ce9107a7fcbbb686
