### ISSUE TITLE
Users are experiencing unexpected sign outs 

### ISSUE THREAD

**Issue by rauhryan** [huboard/huboard-web#168]
Possible causes:

  - OAuth token is mysteriously getting revoked by GitHub
  - We have some weird cookie bug that I'm too noob to understand about
  - Other???

Possible fixes:

  - Sliding window expiration on our cookies
  - Talk to the gitter guys, they don't seem to every have this issue
  - user multiple OAuth applications (one for public one for private)

**Comment by discorick** [comment]
related to https://github.com/huboard/huboard/issues/624
