### ISSUE TITLE
Improve Login Flow

### ISSUE THREAD

**Issue by discorick** [huboard/huboard-web#172]
Good enough:
  - [x] Change the copy of the "Sign in" button to an icon button with the octocat and "Sign in with GitHub" - @discorick 
  - [x] /login Simplify the two step process with just [Sign in with GitHub] - @discorick 
  - [x] /login Add (Green icon) Your email to the permissions asked for - @discorick 
  - [x] "Sign in with github button" Change it's default behavior to "public" scope + email - @discorick 
  - [x] Force a re-auth for all _new_ "login" clicks
  - [ ] Move public vs private to separate OAuth applications - @rauhryan
  - [ ] Store credentials in couchdb (must be encrypted)
  - [ ] Change copy on pricing page to say we store tokens with XYZ encryption and never look at your data without your expressed permission
  - [x] Ensure that email that is collected is making it into intercom [#1 criteria for acceptance] 
  - [x] Sense public auth only on the dashboard and provide an upgrade option - @discorick 

Better:
  - [ ] Skip /login all together and default to "Email scope" 
  - [ ] [DASHBOARD]  If we only have the "email" scope, the landing page should be a "Welcome" here's how you get started similar to what [/login] does today. ![uploads/749cceb6-3b13-4550-9416-94f083f33aa3/huboard_huboard-web_172_pdf__1_page_.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F749cceb6-3b13-4550-9416-94f083f33aa3%2Fhuboard_huboard-web_172_pdf__1_page_.png)
  - [x] [DASHBOARD] If we know they only have Public access, have an option to upgrade to private ("Not seeing your private repositories? [Upgrade access] [?]"

**Comment by rauhryan** [comment]
@discorick if you need further inspiration or ideas, refer to https://libraries.io for general UX ideas

**Comment by drusellers** [comment]
> Store credentials in couchdb (must be encrypted)

Ohhh!!! :+1:

**Comment by drusellers** [comment]
I'd love to review the encryption approarch

**Comment by rauhryan** [comment]
keep an eye out for the PR ;)

**Comment by dahlbyk** [comment]
> [Sign in with github button] Change it's default behavior to "public" scope + email

Note that explicitly requesting public scope will actively remove permissions for private scope. You had mentioned having multiple applications for OAuth, does that come into play here? Or is there a way with Warden to just make sure we have at least `read:org` (and `user:email`?) to pass through to the repo list?

> Force a re-auth for all new "login" clicks

I don't understand what you mean by this. What is expected behavior if someone is already logged in?

> Store credentials in couchdb (must be encrypted)

What does this gain us?

**Comment by rauhryan** [comment]
> You had mentioned having multiple applications for OAuth, does that come into play here?

Yes, that is critical! Forgot to add that

**Comment by rauhryan** [comment]
> I don't understand what you mean by this. What is expected behavior if someone is already logged in?

Translation: strangle hold the problem, if a user is already logged in, continue to let them use the application unaffected until with have completed a shippable version of the "better" path

If a user is NOT logged in, force the new path, if they ARE logged in, wait til they get logged out

**Comment by rauhryan** [comment]
> What does this gain us?

Gains us a ton of value

  * We can default anonymous login's to the email scope 
  * then we have who they are 
  * we pull that document out of couch to see what level of credentials they allowed
  * thus giving the user a smoother "login" experience.


Later...

We get the ability to change the state of the system from GitHub webhooks using the "actors" token

This is a MAJOR prerequisite to HuFlow

**Comment by dahlbyk** [comment]
> move public and private access into separate OAuth applications

So we end up with three apps?

1. **HuBoard** app with `read:org,user:email` for initial login to see dashboard and read-only boards
2. **HuBoard Public** app with `public_repo` to make public repo boards read/write
3. **HuBoard Private** app with `repo` to make private repo boards read/write

Or with two apps we would presumably combine 2 into 1?

Assuming we want to keep the existing HuBoard app as the "main" one, I'm wondering what the ideal UX is to get through the "now we need email" transition. If we ask for `read:org,user:email` without logging out will it leave the existing `public_repo`/`repo` permissions intact or at that point will a second authorization be required?

-------------------------------------------------


> > > Store credentials in couchdb (must be encrypted)
> > 
> > What does this gain us?
> 
> Gains us a ton of value

This feels like a large enough engineering effort (doing this right is a Big Deal™) that it's worth breaking out separate from an initial effort to get email addresses into Intercom. What are the incremental steps we can take to achieve the short-term goal (contact info) in alignment with this future vision?

**Comment by rauhryan** [comment]
> So we end up with three apps?
> 
> HuBoard app with read:org,user:email for initial login to see dashboard and read-only boards
> HuBoard Public app with public_repo to make public repo boards read/write
> HuBoard Private app with repo to make private repo boards read/write

Yes, but we can compromise here til we can get there. End goal is three apps, it might take a few iterations to get there. 



> Assuming we want to keep the existing HuBoard app as the "main" one, I'm wondering what the ideal UX is to get through the "now we need email" transition. If we ask for read:org,user:email without logging out will it leave the existing public_repo/repo permissions intact or at that point will a second authorization be required?


> Assuming we want to keep the existing HuBoard app as the "main" one,  I'm wondering what the ideal UX is to get through the "now we need email" transition.

Wrong assumption, isn't a requirement. I'm suggesting we phase out the old application completely, new logins will slowly migrate to the new system, in a few weeks we change the cookie name and force the outlier's into the transition

 

> This feels like a large enough engineering effort (doing this right is a Big Deal™) that it's worth breaking out separate from an initial effort to get email addresses into Intercom. What are the incremental steps we can take to achieve the short-term goal (contact info) in alignment with this future vision?

I don't fully understand your statement here. Am I romanticizing the "ease" of encrypting a value in a couch document, because in my head its a very trivial requirement... encrypt a value, decrypt a value, it's a simple get/set method, where is the hidden complexity?

> This feels like a large enough engineering effort (doing this right is a Big Deal™) that it's worth breaking out separate from an initial effort to get email addresses into Intercom.

If `(doing this right is a Big Deal™) ` delays getting emails into Intercom by a week, I will accept that trade off

**Comment by dahlbyk** [comment]
> I don't fully understand your statement here. Am I romanticizing the "ease" of encrypting a value in a couch document, because in my head its a very trivial requirement... encrypt a value, decrypt a value, it's a simple get/set method, where is the hidden complexity?

Actually encrypting and decrypting is easy; managing the keys to do so is not.

> > Assuming we want to keep the existing HuBoard app as the "main" one, I'm wondering what the ideal UX is to get through the "now we need email" transition.
> 
> Wrong assumption, isn't a requirement. I'm suggesting we phase out the old application completely, new logins will slowly migrate to the new system, in a few weeks we change the cookie name and force the outlier's into the transition

I guess my thought is that reusing the existing app might provide the most seamless transition, if asking for `read:org,user:email` does indeed only ask for users to grant email if they have already approved `read:org` and `public_repo`/`repo`. @discorick and I got pretty far down this path last week.

Essentially we would use the existing app to see if we have enough permission to do what we need, and if we don't we would start using the new apps to ask for `public_repo` or `repo`.

> Am I romanticizing the "ease" of encrypting a value in a couch document, because in my head its a very trivial requirement... encrypt a value, decrypt a value, it's a simple get/set method, where is the hidden complexity?

Actually encrypting and decrypting is easy. The challenge is key management.

**Comment by rauhryan** [comment]
> I guess my thought is that reusing the existing app might provide the most seamless transition, if asking for read:org,user:email does indeed only ask for users to grant email if they have already approved read:org and public_repo/repo. @discorick and I got pretty far down this path last week.
> 
> Essentially we would use the existing app to see if we have enough permission to do what we need, and if we don't we would start using the new apps to ask for public_repo or repo.

Too complicated... no time, I've considered all the trade-offs, the slow migration with a final cookie name change is the way we're going, it's a risk we are going to take

> Actually encrypting and decrypting is easy. The challenge is key management.

Is this blocking? How long can we go with single private/public key pair in ENV vars before we ABSOLUTELY need to start rotating out the keys?

**Comment by dahlbyk** [comment]
> > Actually encrypting and decrypting is easy. The challenge is key management.
> 
> Is this blocking? How long can we go with single private/public key pair in ENV vars before we ABSOLUTELY need to start rotating out the keys?

How long? Until someone gets their hands on the key. https://www.owasp.org/index.php/Cryptographic_Storage_Cheat_Sheet is a good summary of the considerations running through my head.

For now, I would strongly recommend that we not take on storing the token, but start capturing other stuff into Couch. Account info, email, granted scopes (so we can infer what to ask for), maybe an access log?

**Comment by rauhryan** [comment]
> For now, I would strongly recommend that we not take on storing the token, but start capturing other stuff into Couch. Account info, email, granted scopes (so we can infer what to ask for), maybe an access log?

Ok, I'll take that into consideration.

We should take further security and key storage talks offline

**Comment by discorick** [comment]
How's this look?

![image](https://cloud.githubusercontent.com/assets/1130665/12594300/05ca32ee-c43b-11e5-8665-e7a8edbc542e.png)

**Comment by dahlbyk** [comment]
Aren't private repos shown via `read:org` regardless? Or are we going to start hiding private repos that aren't trial/paid?

**Comment by discorick** [comment]
No, only with private scope - if you login with public scope only HuBoard cannot see any private repos.

**Comment by dahlbyk** [comment]
Right you are. I must be losing my mind.

**Comment by dahlbyk** [comment]
> How's this look?

Does/should the Private repo tab change at all? Clicking it will also trigger a Private auth request, but we don't really give any indication that's going to happen. Or maybe that's by design?

**Comment by rauhryan** [comment]
@huboard/committers  I'm going to put on my anal retentive pedantic hat for a second

* puts on hat * :stuck_out_tongue_closed_eyes: 

as developers we love to Camel Case Shit

For a consistent look and feel across all of HuBoard's copy I try really hard to fight that tendency in myself. 

It's about `consistency`, `tone of voice` and `intent` 

> Looking for Private Repos?

Perhaps better written as...

> Not finding your private repositories?    

or

> Looking for your private repositories?

* takes off hat *

This is not something I'm upset about, I'm not going to pretend to be an expert either, because I'm not. 

I just want to make sure the team is mindful of how we are communicating to our users, let's not sound like jargon using robot's, let's be humans :smile: 

That is all

**Comment by dahlbyk** [comment]
We're already on "your" page, so I'd suggest

> Looking for private repositories?

Is it just me or is button text small relative to the size of the button?

**Comment by rauhryan** [comment]
buttons could use an overhaul, not going to worry about it now. 

That's a larger scoped problem than you would think

**Comment by dahlbyk** [comment]
I don't doubt it, more a random observation than a request for immediate fix.

**Comment by dahlbyk** [comment]
N.B. GitHub seems to have fixed the public "downgrade" issue we were seeing while testing this stuff. Specifically:

#### Old Behavior

1. From `/login`, hit `/login/private`
2. Authorize
3. Confirm Private access
4. Logout
5. From `/login`, hit `/login/public`
6. Authorize asks to revoke Private access
7. Approve and Private access is gone

#### New Behavior

1. From `/login`, hit `/login/private`
2. Authorize
3. Confirm Private access
4. Logout
5. From `/login`, hit `/login/public`
6. Authorize passes through
7. Confirm Private access remains

----

There may still be value in splitting out an initial email-only auth, if we wanted to completely disallow anonymous access, but I no longer see any need to split public/private.

**Comment by discorick** [comment]
@dahlbyk have you confirmed this change with the API team ? I am interested in whether it will be persistent - or if they are A/B testing (happens), additionally we need to keep in mind that if this a subtle API update it will still take time to filter down to enterprise

**Comment by dahlbyk** [comment]
> have you confirmed this change with the API team?

I have not. This seems more like a bug they fixed than a feature they would A/B test.

> additionally we need to keep in mind that if this a subtle API update it will still take time to filter down to enterprise

Is selecting public scope even an option for Enterprise?

**Comment by discorick** [comment]
> is selecting public scope even an option for Enterprise ? 

I am actually not sure, @rauhryan do you know the answer to this one ?

**Comment by dahlbyk** [comment]
OK, @rauhryan, I think I reproduced the login weirdness you are seeing:

1. Revoke application
2. `/login/public` & allow
3. Nothing private on dashboard
4. Click on Private tab & allow
5. Private stuff on dashboard
6. Logout
7. `/login/public`
8. Private stuff still on dashboard -- so far, so good
9. Close & reopen browser
10. **Private stuff *missing* from dashboard**
11. Click on Private tab (no GitHub/allow round trip necessary)
12. Private stuff back on dashboard
13. Close & reopen browser
14. Private stuff still on dashboard

I think we can solve this simply by checking a user data store (or, in the short term, a cookie?) of the most recent scope.

**Comment by dahlbyk** [comment]
And now the more severe repro that seems likely to overlap with https://github.com/huboard/huboard-web/issues/168 and https://github.com/huboard/huboard/issues/624:

1. Open two HuBoard sessions in different browsers (or use Incognito/Private for one)
2. Ensure both are logged out
3. In browser 1
   1. `/login/private` (& allow, if necessary)
   2 .Private stuff on dashboard
4. In browser 2
   1. `/login/public`
   2. Click on a private repo :boom:
   3. Click on Private tab -- empty!
   4. `/login/private` -- no effect! This, in particular, may have been introduced in https://github.com/huboard/huboard-web/pull/254#issuecomment-204010695
