### ISSUE TITLE
Continuous Delivery per Pull Request on Heroku 

### ISSUE THREAD

**Issue by discorick** [huboard/huboard-web#183]
https://devcenter.heroku.com/articles/github-integration-review-apps

**Comment by dahlbyk** [comment]
So I got Heroku review apps set up on #201....and GitHub OAuth rejects auth because the URL doesn't match. This is...unfortunate.
<img width="538" alt="firefox_2016-02-09_01-11-38" src="https://cloud.githubusercontent.com/assets/133987/12909772/2ed3bc16-ceca-11e5-9e2e-7df324d16ec7.png">

**Comment by dahlbyk** [comment]
I mentioned this challenge to @Steven-Pingel and he directed me toward http://stackoverflow.com/a/32544022/54249. We should be able to use `HEROKU_APP_NAME` and `HEROKU_PARENT_APP_NAME` to effectively direct per-PR authorizations through the parent repo.

**Comment by dahlbyk** [comment]
Looks like we're going to have to replace [`Warden::GitHub::Config.normalized_uri()`](https://github.com/atmos/warden-github/blob/3e9aa5fa55d52a0cf8d0cd69ecfb07ce1d5fc03a/lib/warden/github/config.rb#L115-L122), which is hard-coded to build `redirect_uri` from `request.url`.

**Comment by dahlbyk** [comment]
Now that the relevant code has been shipped, review apps can be deployed from https://dashboard.heroku.com/apps/huboard-rails/deploy/github. PRs without the new app.json (and relevant Warden code) won't work, so we'll want to pull `master` into any open branches that we want to review.
