### ISSUE TITLE
Fullscreen breadcrumbs for linked issues is not working from the parent repository

### ISSUE THREAD

**Issue by rauhryan** [huboard/huboard-web#187]
![uploads/833fd8a5-4646-4770-be22-8409973c3ed2/huboard_huboard_HuBoard.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F833fd8a5-4646-4770-be22-8409973c3ed2%2Fhuboard_huboard_HuBoard.png)

Steps to reproduce:

  1. Open huboard/huboard
  2. Find issue huboard/huboard-web#186
  3. Notice the fullscreen breadcrumbs is not correct

Possible causes: 

  * Columns from linked repositories doesn't rely on the hardened array index but instead on the user entered label name index. 
  * Columns are based on a string comparison?

![uploads/b6a3a408-dd0a-4cb9-96fb-3f42294abe09/Labels_·_huboard_huboard-web_and_Labels_·_huboard_huboard_png.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb6a3a408-dd0a-4cb9-96fb-3f42294abe09%2FLabels_%C2%B7_huboard_huboard-web_and_Labels_%C2%B7_huboard_huboard_png.png)

Expected results:

See picture above, give that both repositories have the same column names, we should treat them equally based on `real index`

**Comment by discorick** [comment]
Looks like a WIP problem with linked repositories, after syncing WIP's between repos heres how it looks:
 
![uploads/5b0703d1-6db3-42e8-9546-dc56a8ba1db2/huboard_huboard_HuBoard.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F5b0703d1-6db3-42e8-9546-dc56a8ba1db2%2Fhuboard_huboard_HuBoard.png)

**Comment by rauhryan** [comment]
Is it possible to make it work regardless of the string name
