### ISSUE TITLE
Login Error If Emails Not Found

### ISSUE THREAD

**Issue by dahlbyk** [huboard/huboard-web#190]
The login jobs introduced by #182 are failing periodically with:

> no implicit conversion of String into Integer
>
> /app/vendor/engines/saas/app/jobs/login_private_job.rb:5 []
> /app/vendor/engines/saas/app/jobs/login_private_job.rb:5 block in perform
> /app/vendor/engines/saas/app/jobs/login_private_job.rb:5 each
> /app/vendor/engines/saas/app/jobs/login_private_job.rb:5 detect
> /app/vendor/engines/saas/app/jobs/login_private_job.rb:5 perform

The failing users show a Not Found payload instead of the expected array -

```json
          emails: {
            "message": "Not Found",
            "documentation_url": "https://developer.github.com/v3"
          }
```

**Comment by rauhryan** [comment]
yep, it's a behavior of the GitHub API and it's a side effect of how I built ghee

The lazy nature of the library makes it easy to fall into some of these traps.
