### ISSUE TITLE
Default Templates for New issues

### ISSUE THREAD

**Issue by discorick** [huboard/huboard-web#206]
Give HuBoard the ability to use new issue templates as per https://github.com/dear-github/dear-github/issues/125

Official docs: https://help.github.com/articles/creating-an-issue-template-for-your-repository/
Announcement: https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by dahlbyk** [comment]
It would be awesome if the API exposed `/repos/:owner/:repo/issue_template` in imitation of [`/repos/:owner/:repo/readme`](https://developer.github.com/v3/repos/contents/#get-the-readme). (Analogs for CONTRIBUTING and PULL_REQUEST_TEMPLATE would make sense as well.) As it stands, we'll have to make a couple API queries to track down the file.

@bleikamp, since you announced the feature, do you know if this is on the radar?

**Comment by discorick** [comment]
In lieu of an API endpoint, and for enterprise installs I think this will be the simplest path towards putting this together:

- After board load kick of a client-side async request for an issue_template belonging to each repo
- Use https://developer.github.com/v3/repos/contents/#get-contents to get contents in each project root
- Run a match against files looking for any form of issue_template (its case insensitive)
  - If _not_ found rinse and repeat but look in `.github` dir (as per the docs_
  - If found capture the filename and make another API call for the specific contents of the file
- Resolve a successful request with the raw file contents and save them into a `issue_template` key on that repo

When a fullscreen issue is created we can now apply the template for whichever repo the issue is being created on...

Another UX consideration is this feature should disable the issue quick create.

**Comment by dahlbyk** [comment]
> In lieu of an API endpoint, and for enterprise installs I think this will be the simplest path towards putting this together...

:grinning: https://github.com/huboard/huboard-web/compare/dahlbyk/issue_template

> Another UX consideration is this feature should disable the issue quick create.

:+1:
