### ISSUE TITLE
Bump to Rails 4.2.5.2

### ISSUE THREAD

**Issue by dahlbyk** [huboard/huboard-web#219]
@seanlinsley [suggests](https://github.com/huboard/huboard-web/pull/217#issuecomment-193376818) we should upgrade for security fixes. I agree.

Rails version needs to be bumped both in the root `Gemfile` and in `saas.gemspec`.

**Comment by seanlinsley** [comment]
Here are links to the release notes for [4.2.5](http://weblog.rubyonrails.org/2015/11/13/Rails-4-2-5-and-4-1-14-have-been-released/), [4.2.5.1](http://weblog.rubyonrails.org/2016/1/25/Rails-5-0-0-beta1-1-4-2-5-1-4-1-14-1-3-2-22-1-and-rails-html-sanitizer-1-0-3-have-been-released/), and [4.2.5.2](http://weblog.rubyonrails.org/2016/2/29/Rails-4-2-5-2-4-1-14-2-3-2-22-2-have-been-released/)

**Comment by dahlbyk** [comment]
Closed by #286
