### ISSUE TITLE
Faye Rack Adapter Initialization Error

### ISSUE THREAD

**Issue by dahlbyk** [huboard/huboard-web#221]
When #214 was deployed there were two new app initialization errors:

> Message: wrong number of arguments (1 for 0)
> 
> Backtrace:
> 
> ```
> /app/vendor/bundle/ruby/2.2.0/gems/faye-1.1.1/lib/faye/adapters/rack_adapter.rb:72 initialize
> /app/vendor/bundle/ruby/2.2.0/gems/faye-1.1.1/lib/faye/adapters/rack_adapter.rb:72 new
> /app/vendor/bundle/ruby/2.2.0/gems/faye-1.1.1/lib/faye/adapters/rack_adapter.rb:72 get_client
> /app/vendor/bundle/ruby/2.2.0/gems/faye-1.1.1/lib/faye/adapters/rack_adapter.rb:80 call
> /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/etag.rb:24 call
> /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:25 call
> /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13 call
> /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/params_parser.rb:27 call
> /app/vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:35 block in call
> /app/vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34 catch
> /app/vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34 call
> /app/config/initializers/warden.rb:72 call
> /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/flash.rb:260 call
> ```

-----

> Message: Circular dependency detected while autoloading constant JobResolver
> 
> Backtrace:
> 
> ```
> /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:492 load_missing_constant
> /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:184 const_missing
> /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:526 load_missing_constant
> /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:184 const_missing
> /app/app/controllers/application_controller.rb:44 queue_job
> /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:432 block in make_lambda
> /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:239 call
> /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:239 block in halting
> /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:506 call
> /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:506 block in call
> /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:506 each
> /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:506 call
> /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:92 __run_callbacks__
> /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778 _run_process_action_callbacks
> /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81 run_callbacks
> /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/abstract_controller/callbacks.rb:19 process_action
> /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/rescue.rb:29 process_action
> /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb:32 block in process_action
> /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164 block in instrument
> /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20 instrument
> /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164 instrument
> /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb:30 process_action
> /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/params_wrapper.rb:250 process_action
> /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/abstract_controller/base.rb:137 process
> /app/vendor/bundle/ruby/2.2.0/gems/actionview-4.2.4/lib/action_view/rendering.rb:30 process
> /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal.rb:196 dispatch
> /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/rack_delegation.rb:13 dispatch
> /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal.rb:237 block in action
> /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:76 call
> /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:76 dispatch
> /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:45 serve
> /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:43 block in serve
> /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:30 each
> /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:30 serve
> /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:821 call
> /app/vendor/bundle/ruby/2.2.0/gems/ember-rails-assets-0.1.1/lib/ember/rails/assets/middleware.rb:8 call
> /app/vendor/bundle/ruby/2.2.0/gems/pdfkit-0.6.2/lib/pdfkit/middleware.rb:17 call
> /app/vendor/bundle/ruby/2.2.0/gems/rack-attack-4.2.0/lib/rack/attack.rb:104 call
> /app/vendor/bundle/ruby/2.2.0/gems/faye-1.1.1/lib/faye/adapters/rack_adapter.rb:81 call
> /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/etag.rb:24 call
> /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:25 call
> /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13 call
> /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/params_parser.rb:27 call
> /app/vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:35 block in call
> /app/vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34 catch
> /app/vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34 call
> /app/config/initializers/warden.rb:72 call
> /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/flash.rb:260 call
> ```

**Comment by rauhryan** [comment]
There occur every once in a great moon, because we don't have full control over Heroku restarts and rails has really complicated strange issues that can occur with autoloading constants

**Comment by dahlbyk** [comment]
So this is probably just a false alarm? Wanted to call it out since there's a new middleware.

**Comment by dahlbyk** [comment]
Just deployed without issue. ¯\_(ツ)_/¯
