### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by seanlinsley** [huboard/huboard-web#235]
https://huboard.com/

<img width="325" alt="screen shot 2016-03-14 at 4 40 30 pm" src="https://cloud.githubusercontent.com/assets/688886/13760936/a03ba946-ea03-11e5-9e68-411b249a1e93.png">

It looks like the status page isn't configured correctly, because it isn't showing an error: http://status.huboard.com/

<img width="870" alt="screen shot 2016-03-14 at 4 40 39 pm" src="https://cloud.githubusercontent.com/assets/688886/13760937/a04050d6-ea03-11e5-9d01-f5d8c425a02e.png">

**Comment by dahlbyk** [comment]
We're looking into it - Heroku seems to be having an issue: https://status.heroku.com/

Good catch on the status page, we'll look into that too.

**Comment by dahlbyk** [comment]
https://status.heroku.com/incidents/867#update-3018

> Engineers continue to investigate the issue. The applications that made releases (including newly created applications) or had cycled are affected. They are unavailable due to issues with incorrect app status reports to routing layer and seeing H10 errors.

I seem to have picked an unlucky time to deploy. :imp:

**Comment by dahlbyk** [comment]
Heroku seems to be recovering. Please let us know if anything else seems amiss.
