### ISSUE TITLE
Flexible column widths is having issues at certain browser widths  

### ISSUE THREAD

**Issue by rauhryan** [huboard/huboard-web#332]

**Comment by rauhryan** [comment]
- check for @media queries that are the possible cause?
 - possibly a chrome on windows problem?

**Comment by dahlbyk** [comment]
Can you provide any more detail here? What widths? Support ticket re: Chrome on Windows?

**Comment by rauhryan** [comment]
Jotting down some quick notes, so I don't forget.

Related to ZenDesk ticket 1203 - Feedback from Patrick 

Don't want to post the screenshot has their private data.
