### ISSUE TITLE
Drag avatar to assign is currently broken in master

### ISSUE THREAD

**Issue by rauhryan** [huboard/huboard-web#334]
## Steps to reproduce

Drag an avatar from the filters onto a card

## Expected

It should assign or add to the assignees

## Results

An exception is throw in because it is calling the old assignUser method on the Issue model

 

Please open new issues for HuBoard [here](https://github.com/huboard/huboard/issues/new)
_contact_ support@huboard.com _for personal support on critical issues_

**Comment by discorick** [comment]
@rauhryan Happy to knock this out today... should I open the PR against card-redesigns ?
