### ISSUE TITLE
Card disappearing on reorder

### ISSUE THREAD

**Issue by discorick** [huboard/huboard-web#341]
Ran into a case where a care disappears on every move, then reappears  when a render is forced on on the milestones view:

![uhoh](https://cloud.githubusercontent.com/assets/1130665/16957786/196702ca-4d9b-11e6-9f15-5ee3d784f6fa.gif)

The card below meta-data (test-issue#7)
![image](https://cloud.githubusercontent.com/assets/1130665/16957813/3707c6b6-4d9b-11e6-946c-311e19428ab3.png)

The card above meta-data (test-issue#6)
![image](https://cloud.githubusercontent.com/assets/1130665/16957854/58ea3f0c-4d9b-11e6-90e8-b384f8e9b8e4.png)

The meta-data of the card being moved:
![image](https://cloud.githubusercontent.com/assets/1130665/16957868/6a23dae4-4d9b-11e6-90cd-fde91e90c919.png)

**Comment by discorick** [comment]
This explains the behavior: https://github.com/huboard/huboard-web/blob/master/ember-app/app/mixins/cards/card-move.js#L21

I created all these issues from the task-view, for some reason they were all assigned the exact same `milestone_order` key values.

**Comment by dahlbyk** [comment]
I'm unclear why this would cause the card to disappear, vs simply failing to reorder (or having nondeterministic order among the three with identical `milestone_order` values).

**Comment by discorick** [comment]
So, to keep glimmer from loosing track of cards in the DOM sortable list - we actually pulling the issue object out of a computed array. You can see here https://github.com/huboard/huboard-web/blob/master/ember-app/app/components/columns/hb-column.js#L14

It seems in this case (maybe because there is no change to the underlying data) the computed list is not rebuilding, which means the card is never placed back into the DOM.
