### ISSUE TITLE
Missing AWS keys prevents deployment

### ISSUE THREAD

**Issue by nz** [huboard/huboard-web#85]
```
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        rake aborted!
remote:        ArgumentError: Missing required arguments: aws_access_key_id, aws_secret_access_key
```

Might consider either making those keys optional, and feature-flag the related functionality accordingly, or adding a bit to the deployment documention on the use and recommended IAM policy for those keys. Happy to pursue and contribute one or the other.

**Comment by nz** [comment]
The warning message for lack of Stripe API key seems like an appropriate example here:

```
No stripe.com API key was configured for environment production! this application will be
unable to interact with stripe.com. You can set your API key with either the environment
variable `STRIPE_SECRET_KEY` (recommended) or by setting `config.stripe.secret_key` in your
environment file directly.
```

**Comment by rauhryan** [comment]
Ah makes sense. 

The image upload doesn't work if you don't have aws keys

But it is behind a feature flag. 

https://github.com/huboard/huboard-web/blob/master/features.json

Change IMAGE_UPLOAD to false

RE: Stripe API

I think you can set and ENV

`HUBOARD_ENV=oss`

It might still throw a warning but you can ignore it

**Comment by rauhryan** [comment]
[Trip Details.pdf](https://github.com/huboard/huboard-web/files/2661/Trip.Details.pdf)

**Comment by discorick** [comment]
We have updated the wiki page and the default sample env.example to make local deployment setup  less error prone
